config/routes.rb
WebProyect::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end 

  resources :concerts
  get 'Homepage', to: "concerts#index", as: :homepage
  root :to => "concerts#index"

  resources :users do 
    resources :follows
  end

end

app/models/concert.rb
class Concert < ActiveRecord::Base
  attr_accessible :date, :full_desc, :name_art, :price, :song, :time_dur, 
                  :title, :user_id, :poster

  validates_presence_of :title, :date, :full_desc, :name_art, :user_id

  has_attached_file :poster, :styles => { :medium => "400x400", 
                    :thumb => "140x140>" }

  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  attr_accessible :user, :follower, :user_id, :follower_id
  
  belongs_to :user
  belongs_to :follower, :class_name => "User"

  validates_presence_of :user_id, :follower_id
  validates_uniqueness_of :user_id, :scope => :follower_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :full_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :concerts
  
  has_many :follower_follow, :class_name => "Follow"
  has_many :followers, :through => :follower_follow

  has_many :followed_follow, :class_name => "Follow", :foreign_key => :follower_id
  has_many :followeds, :through => :followed_follow, :source => :user_id


  def concert_followed
    Concert.where(:user_id => followeds)
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :authenticate_same_user, :only => [:update, :destroy, :edit]

  def authenticate_same_user
    @concert = Concert.find(params[:id])
      if current_user == @concert.user
        true
      else
        redirect_to concert_path(@concert), :alert => "You are not authorized to edit this post"
      end
  end
  
  def index
    @concerts = Concert.order("created_at DESC").page(params[:page]).per(6)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @concerts }
    end
  end

  def show
    @concert = Concert.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @concert }
    end
  end 

  def new
    @concert = Concert.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @concert }
    end
  end

  def create
    @concert = Concert.new(params[:concert])

    respond_to do |format|
      if @concert.save
        format.html { redirect_to @concert, notice: 'Post of Concert was successfully created.' }
        format.json { render json: @concert, concert: :created, location: @concert }
      else
        format.html { render action: "new" }
        format.json { render json: @concert.errors, concert: :unprocessable_entity }
      end
    end
  end

  def edit
    @concert = Concert.find(params[:id])
  end

  def update
    @concert = Concert.find(params[:id])

    respond_to do |format|
      if @concert.update_attributes(params[:concert])
        format.html { redirect_to @concert, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @concert.errors, concert: :unprocessable_entity }
      end
    end
  end

  def destroy
    @concert = Concert.find(params[:id])
    @concert.destroy

    respond_to do |format|
      format.html { redirect_to concerts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def new 
    @user = User.find(params[:user_id])
    @follow = Follow.new
    @follow.user_id = @user.id
    @follow.follower_id = current_user.id
    @follow.save 

    respond_to do |format|
      format.html{redirect_to concerts_path, notice: "jjejej"}
      format.js 
    end 
  end

  def destroy
    @user = User.find(params[:user_id])
    @follow = Follow.find(params[:id])
    @follow.destroy

    respond_to do |format|
      format.html{redirect_to concerts_path, notice: "se jue"}
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
    when :alert
      "alert-error"
    when :notice
      "alert-success"
    else
      ""
    end
  end
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/concerts/_form.html.erb
<% if user_signed_in? %>
  <%= simple_form_for(@concert, html: {class: "form-horizontal"}) do |f| %>
    <% if @concert.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@concert.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @concert.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id, :value => current_user.id %>

    <p>Name Concert</p>
    <%= f.input :title, :label => '-' %>
    <p>________</p>
    <div class="field">
      <%= f.input :poster, as: :file %>
    </div>
    <p>________</p>
    <p>Date</p>
    <td><%= f.text_field :date, :id => "datepicker" %></td>
    <p>________</p>
    <p>Time Concert Details </p>
    <%= f.input :time_dur, :label => '-' %>
    <p>________</p>
    <p>Price </p>
    <%= f.input :price, :label => '-' %>
    <p>________</p>
    <p> Guest Artist </p>
    <%= f.input :name_art, :label => '-' %>
    <p>________</p>
    <p> Sample Song </p>
    <%= f.input :song, collection: [@concert.song] %>
    <p>________</p>
    <p>Concert Details </p>
    <%= f.input :full_desc, :label => '-' %>

    <div class="form-actions">
      <%= f.button :submit, "Publish Concert Info", class: "btn btn-info" %>
    </div>
  <% end %>
<% end %> 

app/views/concerts/edit.html.erb
<h1>Update Concert</h1>

<%= render 'form' %>

<%= link_to 'Show', @concert,  class: "btn btn-primary"%> |
<%= link_to 'Back', concerts_path, class: "btn btn-info" %>

app/views/concerts/index.html.erb
<div class="page-header">
  <h1>All Concerts</h1>
</div>
 
<% @concerts.each do |concert| %>
  <div class="row-fluid">
    <div class="span2">
      <% unless concert.poster_file_name.nil?%>
        <%= image_tag(concert.poster.url(:thumb), class: "img-polaroid") %>
      <% end%>
    </div>
    <div class="span10">
      <div class="concert">
        <h3><%= link_to concert.title, concert %></h3>
          <p>Day of de Event: <%= concert.date.strftime("%d-%m-%Y") %></p>
          <p>Guest artis: <%= concert.name_art %></p>
          <p>Price: USD <%= concert.price %></p>
            post by <%= concert.user.full_name %> | <%= concert.created_at.strftime("%d-%m-%Y")  %> |
            <% unless user_signed_in? && concert.user == current_user%>
            <div class="following<%=concert.user.id%> line">
              <% if concert.user.followers.blank? %>
                <%= link_to "Follow #{concert.user.full_name}", new_user_follow_path(concert.user),remote: true, class: "btn btn-primary btn-small" %>  
              <% else %>
                <% foll = Follow.where("follower_id = #{current_user[:id]} and user_id = #{concert.user.id}").first
                %>
                <%= link_to "Unfollow #{concert.user.full_name}", user_follow_path(concert.user,foll),method: :delete, remote: true, class: "btn btn-small" %>  
              <% end %> 
            </div>
            <% end %>
            <% if current_user == concert.user %>
            <span class = "admin">
              | <%= link_to 'Edit', edit_concert_path(concert), class: "btn btn-warning" %>
              | <%= link_to 'Delete', concert, method: :delete, data: { confirm: 'Are you sure Delete this status?' }, class: "btn btn-danger" %>
            </span>
            <% end %>
      </div>
    </div>
  </div> 
<% end %>

<%= paginate @concerts%>

app/views/concerts/new.html.erb
<h1>New Concert</h1>

<h3>Complete data Concert</h3>

<%= render 'form' %>

<%= link_to 'Back', concerts_path, class: "btn btn-info" %>

app/views/concerts/show.html.erb
    <p>
      <b><h3><%= @concert.title %></h3></b>
    </p>
<div class="row-fluid">
  <div class="span5">
    <%= image_tag @concert.poster.url(:medium) if !@concert.poster_file_name.nil? %>
  </div>
  <div class="span7">
    
    <p>
      <h5>Guest Artist:  <%= @concert.name_art %></h5>
    </p>
    <p>
      Consert day <%= @concert.date.strftime("%d-%m-%Y") %>
    </p>
    <p>
      <%= @concert.full_desc %>
    </p>
    <p>
      Onset and Duration <%= @concert.time_dur %>
    </p>
    <p>
      <h5>Price: USD <%= @concert.price %></h5>
    </p>  
    <p>
      <h5>by <%= @concert.user.full_name %></h5>
    </p>
  </div>
</div>
<% unless @concert.song.blank? %>
<div class="container">
  <p>
  <h5>Sample Song</h5>
  </p>     
  <% client = Soundcloud.new(client_id: 'e39a5e9dec883d7b2507d6dbb47887d2') %>
  <% embed_info = client.get('/oembed', url: @concert.song) %>
  <%= embed_info['html'].html_safe %>
</div>
<% end %>
<p>
  <% if user_signed_in? && (current_user == @concert.user) %>
    <%= link_to 'Edit Post', edit_concert_path(@concert), class: "btn btn-warning btn-small" %>
  <% end %>
</p>

<%= link_to 'Back', concerts_path, class: "btn btn-info" %>

app/views/follows/destroy.js.erb
$(".following<%=@user.id%>").html('<%= link_to "Follow #{@user.full_name}", new_user_follow_path(@user),remote: true, class: "btn btn-primary btn-small" %>');

app/views/follows/new.js.erb
$(".following<%=@user.id%>").html('<%= link_to "Unfollow #{@user.full_name}", user_follow_path(@user,@follow),method: :delete, remote: true, class: "btn btn-small" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebProyect</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />
    <script src="//connect.soundcloud.com/sdk.js"></script>
    <script>
      SC.initialize({
        client_id: "e39a5e9dec883d7b2507d6dbb47887d2"
      });
    </script>
</head>
<body>
  <div class = "navbar navbar-fixed-top">  
    <div class = "navbar-inner">  
      <div class = "container">    
        <a href = "#" class = "brand"> Traveller Wolf </a>
          <ul class ="nav">
            <li><%= link_to "Homepage ", homepage_path %></li>
          </ul>
          <ul class ="nav">
            <% if user_signed_in? %>
              <li><%= link_to 'New Concert', new_concert_path %></li>
            <% end %>
          </ul>
          <ul class ="nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to current_user.full_name, edit_user_registration_path %></li>
              <li><%= link_to "Log Out ", logout_path %></li>
            <% else %>
              <li><%= link_to "Register ", register_path %></li>
              <li><%= link_to "Log In ", login_path %></li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>

  <div class = "container">
    <% flash.each do |type, message| %>
      <div class = "alert <%= flash_class type %>">
        <button class="close" data-dismiss="alert">x</button>
        <%= message %>  
      </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>